import { Router } from 'express';
import { getDashboard, getNotes, triggerIndex, getTimeline, getCalendar, getNoteById, searchNotes, getConfig, updateConfig, getIndexStatus, getIndexErrors, listAiPrompts, updateAiPrompt, resetAiPrompt, getAiProviderHandler, updateAiProviderHandler, testAiProviderHandler, listAiSuggestionsHandler, updateNote, appendNote, createNote, deleteNote, getStatsTrend, getStatsRadar, getStatsMonthly, getStatsTags, createWorkerTaskHandler, getWorkerTaskHandler, listWorkerTasksHandler, retryWorkerTaskHandler, cancelWorkerTaskHandler, clearFinishedWorkerTasksHandler, createScheduleHandler, listSchedulesHandler, getScheduleHandler, updateScheduleHandler, deleteScheduleHandler, runScheduleNowHandler, scheduleHealthHandler, listSoulActionsHandler, getSoulActionHandler, approveSoulActionHandler, dispatchSoulActionHandler, deferSoulActionHandler, discardSoulActionHandler, listReintegrationRecordsHandler, acceptReintegrationRecordHandler, rejectReintegrationRecordHandler, planPromotionsHandler, listEventNodesHandler, listContinuityRecordsHandler } from './handlers.js';

export const router = Router();

router.get('/dashboard', getDashboard);
router.get('/notes', getNotes);
router.get('/notes/:id', getNoteById);
router.get('/timeline', getTimeline);
router.get('/calendar', getCalendar);
router.get('/search', searchNotes);
router.get('/config', getConfig);
router.post('/config', updateConfig);
router.post('/index', triggerIndex);
router.get('/index/status', getIndexStatus);
router.get('/index/errors', getIndexErrors);
router.get('/ai/prompts', listAiPrompts);
router.patch('/ai/prompts/:key', updateAiPrompt);
router.delete('/ai/prompts/:key', resetAiPrompt);
router.get('/ai/provider', getAiProviderHandler);
router.patch('/ai/provider', updateAiProviderHandler);
router.post('/ai/provider/test', testAiProviderHandler);
router.get('/ai/suggestions', listAiSuggestionsHandler);
router.post('/worker-tasks', createWorkerTaskHandler);
router.delete('/worker-tasks/finished', clearFinishedWorkerTasksHandler);
router.get('/worker-tasks', listWorkerTasksHandler);
router.get('/worker-tasks/:id', getWorkerTaskHandler);
router.post('/worker-tasks/:id/retry', retryWorkerTaskHandler);
router.post('/worker-tasks/:id/cancel', cancelWorkerTaskHandler);
router.get('/soul-actions', listSoulActionsHandler);
router.get('/soul-actions/:id', getSoulActionHandler);
router.post('/soul-actions/:id/approve', approveSoulActionHandler);
router.post('/soul-actions/:id/dispatch', dispatchSoulActionHandler);
router.post('/soul-actions/:id/defer', deferSoulActionHandler);
router.post('/soul-actions/:id/discard', discardSoulActionHandler);
router.get('/reintegration-records', listReintegrationRecordsHandler);
router.post('/reintegration-records/:id/accept', acceptReintegrationRecordHandler);
router.post('/reintegration-records/:id/reject', rejectReintegrationRecordHandler);
router.post('/reintegration-records/:id/plan-promotions', planPromotionsHandler);
router.get('/event-nodes', listEventNodesHandler);
router.get('/continuity-records', listContinuityRecordsHandler);
router.post('/schedules', createScheduleHandler);
router.get('/schedules/health', scheduleHealthHandler);
router.get('/schedules', listSchedulesHandler);
router.get('/schedules/:id', getScheduleHandler);
router.patch('/schedules/:id', updateScheduleHandler);
router.delete('/schedules/:id', deleteScheduleHandler);
router.post('/schedules/:id/run', runScheduleNowHandler);
router.post('/notes', createNote);
router.patch('/notes/:id', updateNote);
router.delete('/notes/:id', deleteNote);
router.post('/notes/:id/append', appendNote);
router.get('/stats/trend', getStatsTrend);
router.get('/stats/radar', getStatsRadar);
router.get('/stats/monthly', getStatsMonthly);
router.get('/stats/tags', getStatsTags);
